let users = [
  {
    id: 1,
    name: "Rony Rodriguez",
    username: "RonyRex",
    email: "rony@gmail.com",
    address: "Res. CA, Calle principal.",
    phone: "98351410",
    website: "ronydev.com",
  },
  {
    id: 2,
    name: "Luis Irias",
    username: "Lufexib",
    email: "luis@hotmail.com",
    address: "Col. La quezada por los pollos.",
    phone: "97486512",
    website: "dev-luis.com",
  },
  {
    id: 3,
    name: "Angel Bulnes",
    username: "Abulnes16",
    email: "abulnes@gmail.com",
    address: "Col. Hato del Miedo, Cerca de las carnitas.",
    phone: "95641782",
    website: "abulnes16dev.com",
  },
  {
    id: 4,
    name: "David Flores",
    username: "SucioDave",
    email: "dave15@gmail.com",
    address: "Col. Humuya, Mansión #45",
    phone: "99487893",
    website: "suciodev.com",
  },
  {
    id: 5,
    name: "Mario Zavala",
    username: "Zavala69",
    email: "mzavala@gmail.com",
    address: "Res. La cañada, avenida 13.",
    phone: "94563008",
    website: "zavaladev.com",
  },
  {
    id: 6,
    name: "Luis Andino",
    username: "Luismi",
    email: "andino90@gmail.com",
    address: "Col. 21 de Febrero, calle principal.",
    phone: "95617849",
    website: "andinodev.com",
  },
  {
    id: 7,
    name: "Ana Rivera",
    username: "Anapaulis",
    email: "paulis@gmail.com",
    address: "Col. Catacamas, Calle del morido.",
    phone: "91478963",
    website: "paulisdev.com",
  },
  {
    id: 8,
    name: "Signe Luque",
    username: "Colochos",
    email: "slique@gmail.com",
    address: "Col. Monte Verde, Casa #456.",
    phone: "94979893",
    website: "luquedev.com",
  },
  {
    id: 9,
    name: "Ledys Santos",
    username: "DiosaNordica",
    email: "nordica@gmail.com",
    address: "Res. Omoa, Calle principal.",
    phone: "89647135",
    website: "nordicadev.com",
  },
  {
    id: 10,
    name: "Maria Barahona",
    username: "Majo",
    email: "majo@gmail.com",
    address: "Res. FCO, calle principal",
    phone: "33564978",
    website: "majodev.com",
  },
];

module.exports = users;
